version: '3'

services:
  neo4j:
    image: neo4j:latest
    env_file:
      - './server/.env'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - './db:/data'
  # neo4j:
  #   build: ./server/neo4j
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
  #   environment:
  #   - NEO4J_dbms_security_procedures_unrestricted=apoc.*
  #   - NEO4J_apoc_import_file_enabled=true
  #   - NEO4J_apoc_export_file_enabled=true
  #   - NEO4J_dbms_shell_enabled=true     
  server:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    links:
      - neo4j
    depends_on:
      - neo4j
  client:
    build: ./client
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    links:
      - "server:server"
    depends_on:
      - server

