version: '3'

services:
  server:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
  client:
    build: ./client
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    links:
      - "server:server"

